### ISSUE TITLE
Single Page App or Server Side Rendering plus JavaScript?

### ISSUE THREAD

**Issue by cpritcha** [comses/wagtail-comses.net#1]
Single Page App
---------------------

### Pros

- No reloading of header and footer content between pages
- JSON rest API is better tested because we our application uses all of it
- JavaScript dependencies and code are neatly bundled. Frontend logic is all in JavaScript.

### Cons

- Duplication of code for routing, data structures and validation
- Manual management of history
- More work to get Google Scholar and other services to index the site
- More work to integrate with Wagtail menu system
- Little to nothing works without JavaScript

Server Side Rendering + JavaScript
----------------------------------------------

### Pros

- Use built in Django functionality
- Simple pagination and display

### Cons

- Harder to deal with streaming asynchronous updates (status notifications for model runs or see updates to the main page without a refresh)
- More difficult to determine to what is done by JavaScript and what is done by Django
- JavaScript dependency management is more manual

**Comment by alee** [comment]
going with reactive vue apps in edit forms, server-side rendering for all published content
