### ISSUE TITLE
add alte din font to webpack build

### ISSUE THREAD

**Issue by alee** [comses/wagtail-comses.net#38]
Hey @cpritcha can you add http://www.1001fonts.com/alte-din-1451-mittelschrift-font.html to our webpack build and make it available as a poor person's replacement to Fervor's FF Din font selection? 

There's also https://fontlibrary.org/en/font/u-din-1451-mittelschrift but I would probably prefer to host it locally. I don't mind relying on Google for fonts but not sure how long fontlibrary.org will be around.

**Comment by cpritcha** [comment]
Sure. I'll make it the default font.

**Comment by alee** [comment]
I think open sans is still the default font, this one is just for
announcement headers on the front page and maybe for other headings. We
would have to look at the psds. It's easy enough to change in the scss
though.

I pulled in Abel and the web font which may be good enough.
